### ISSUE TITLE
autolayout: support for v/hgroups

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#10]

**Comment by TiboStr** [comment]
Do you want me to write my own algorithm to auto position nodes? 

Right now I am using [dagre](https://github.com/dagrejs/dagre). It has ok compatibility with ReactFlow, but `vgroup` and `hgroup` are 2 keys I added myself. So I don't think it is possible right now to support `v/hgroup`s in combination with `autoLayout`.

**Comment by bjdmeest** [comment]
I'm guessing you can't ask dagre to do the autolayout without the elements within the nested groups, and then do autolayout individually per nested group?

**Comment by bjdmeest** [comment]
(gets close to your own algorithm then I guess 😅 )

**Comment by TiboStr** [comment]
> I'm guessing you can't ask dagre to do the autolayout without the elements within the nested groups, and then do autolayout individually per nested group?

Ah of course. That is also a possibility.
