### ISSUE TITLE
Be able to 'import' or 'permalink' via (public) url to a JSON config

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#101]
so instead of loading a file, you just give a URL. Same for the permalink: additional to supporting 'raw' JSON as part of the URL, just have a link to an online JSON config file

**Comment by TiboStr** [comment]
- [x] Load in a permalink from someone else
- [x] Encode online location of JSON file
- [x] Update README and CHANGELOG


This is a link to an online config: https://gist.githubusercontent.com/TiboStr/05db9a41779f71267a7315836d1e59ee/raw/7aeb5a3f20de368ebd848728092f93844ca5e2e8/flow-config.json
