### ISSUE TITLE
Be able to easily scroll/navigate larger networks

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#104]
See https://bjdmeest.github.io/dataflow-visualization/ final example: that's a pretty large network and going from top to bottom takes quite some time. Either being able to click on the minimap to jump to the right location or some kind of scrollbars or whatever would be cool.

Example: https://medium.com/@christian_maehler/implementing-a-scrollbar-for-react-flow-29653c2562fd

**Comment by TiboStr** [comment]
2 bugs: 
* The controls disappear when scrolling down
* Cannot zoom when scrollbar is at bottom (if scrollbar is at bottom scrolling has effect on the scrollbar, not on the zooom of the flow)
