### ISSUE TITLE
local property should override preset property

### ISSUE THREAD

**Issue by mvanbrab** [TiboStr/dataflow-visualization#133]
As an example in a node, the resulting fill color should be green, regardless of any fill color defined in the preset:
```
   {
        "id": "thing1",
        "label": "thing 1",
        "preset": "coloredThings",
        "fill": "green"
  }
```

**Comment by TiboStr** [comment]
This is fixed by issue #132 



```json
{
    "graph": {},
    "node": {
        "presets": {
            "preset1": {
                "shape": "8-star",
                "fill": "yellow"
            }
        }
    },
    "edge": {}
}
```


```json
[
    {
        "preset": ["preset1"],
        "fill": "red"
    }
]
```

Result:
![Screenshot_20220901_114430](https://user-images.githubusercontent.com/71405687/187884645-e10ce5d5-961c-460c-a1b2-dacf7a6a26ea.png)


---------------

So the local fill has priority on the fill of the preset.
