### ISSUE TITLE
undo/redo buttons

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#23]
have the possibility to revert back to previous and next valid visualizations

**Comment by TiboStr** [comment]
@bjdmeest, how do you see that with autosync?


I can imagine if you don't use this feature, you 'store' your config every time you click 'convert' (and config is valid). Then you can navigate between your converts with two buttons.


But I don't think there would be a reason to turn autosync off.


Imagine when I want to create just a node with the label 'label'.

### Valid config 1
```json
{"graph":{},"node":{},"edge":{}}
```

```json
[{}]
```

```json
[]
```

### Valid config 2
```json
{"graph":{},"node":{},"edge":{}}
```

```json
[{"label": ""}]
```

```json
[]
```

### Valid config 3
```json
{"graph":{},"node":{},"edge":{}}
```

```json
[{"label": "l"}]
```

```json
[]
```

....


### Valid config 7 (!)
```json
{"graph":{},"node":{},"edge":{}}
```

```json
[{"label": "label"}]
```

```json
[]
```


It would be a bit ridiculous to store 7 states, just for that. 

So what do you suggest? When has a config enough changed to be stored? And how do we expect a user not to be confused by why his/her config has or has not been saved? Perhaps a third button 'store'?

**Comment by bjdmeest** [comment]
Typically a 'debounce' function is used for this: https://www.freecodecamp.org/news/debounce-explained-how-to-make-your-javascript-wait-for-your-user-to-finish-typing-2/, where saving is done asynchronously (so no delay on the autosync updates)
