### ISSUE TITLE
Github CI to generate the build files instead of checking into version control

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#31]
see https://create-react-app.dev/docs/deployment/#github-pages

**Comment by TiboStr** [comment]
Is the purpose of this issue to not have to run `npm run deploy` manually?

This link does not mention anything about continuous integration with GitHub pages. Or should I set up continuous delivery using e.g. [Netlify](https://create-react-app.dev/docs/deployment/#netlify)?


Or Do you mean I have to do this: https://medium.com/front-end-weekly/ci-cd-with-github-actions-to-deploy-on-github-pages-73e225f8f131

**Comment by bjdmeest** [comment]
Ah yes, I meant https://medium.com/front-end-weekly/ci-cd-with-github-actions-to-deploy-on-github-pages-73e225f8f131 , I C-P'd too fast :)
