### ISSUE TITLE
Auto-scale title in a shape

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#33]
basically adapt the fontSize, probably you can calculate that based on the number of characters in the title

**Comment by TiboStr** [comment]
@bjdmeest,

Could you elaborate a bit more? 

![Screenshot_20220826_132506](https://user-images.githubusercontent.com/71405687/186893711-4a5fad45-7fcc-4579-9b62-08475bcbaf49.png)

How would you want the fontSize to be different in example 5? `Solid Pod` is a title.

**Comment by bjdmeest** [comment]
Well, let's say the title is `This is a Solid pod that stores many different RDF blocks nicely next to each other`: decrease the font size so that that still fits within the with of that rectangle :)

**Comment by TiboStr** [comment]
I also auto-scaled `label`s.
