### ISSUE TITLE
Global node and edge settings: make them nested

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#4]
I would make the global settings as follows:

```js
{
  graph: {
    layout: "..."
  },
  node: {
    fill: "...",
    fontSize: "..."
  },
  edge: {
    "..."
  }
}
```

So that it's clear which parameters refer to which parts

**Comment by TiboStr** [comment]
I merged it when this repo was still mine,  so I will close this issue.
