### ISSUE TITLE
strokeDashArray instead of strokeDasharray

### ISSUE THREAD

**Issue by elsdvlee** [TiboStr/dataflow-visualization#52]
detail ...

**Comment by TiboStr** [comment]
Are you sure? `strokeDasharray` is just the camelCase version of the [CSS property `stroke-dasharray`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray).

**Comment by elsdvlee** [comment]
Google tells me that you are right :-)
It felt wrong linguistically.
