### ISSUE TITLE
Document use of button 'Fill in positions into node config'

### ISSUE THREAD

**Issue by elsdvlee** [TiboStr/dataflow-visualization#53]
I imagine that it fills in the positions after dragging the nodes to a different location, which would be a great functionality. However, I cannot make it function. I always get an error code.

**Comment by TiboStr** [comment]
@elsdvlee could you send a screenshot/gif? For me it seems to work fine.

![fill-in-positions](https://user-images.githubusercontent.com/71405687/183585671-2ca7490a-e083-4013-b376-725cd29793b8.gif)

**Comment by elsdvlee** [comment]
![image](https://user-images.githubusercontent.com/93709574/183594085-15380308-1f0f-4f0c-b4ab-ceb9ca86d21e.png)
I tried again: the first examples work, however example 5 and 6 not. I think that maybe the parentNode is causing a problem.
