### ISSUE TITLE
Simulate the activation of certain components

### ISSUE THREAD

**Issue by elsdvlee** [TiboStr/dataflow-visualization#54]
In the simplest form maybe onclick events that toggle hide/show of specific edges and nodes when clicking on specific nodes could simulate that a certain action within the flow is started or ended. I think about the activation of Comunica or Rml mapper/streamer.

**Comment by TiboStr** [comment]
@elsdvlee 
E.g. in this diagram:
![Screenshot_20220810_134601](https://user-images.githubusercontent.com/71405687/183893380-6850e3cb-9ee4-4b4f-a1aa-64327fc56dc8.png)


If I click on `comunica`, what would you want to happen exactly?

Do you want `comunica` and its neighboring edges to be hidden? Do you want a mechanism to make it visible again?

**Comment by elsdvlee** [comment]
In this example initially all edges with arrows and all RDF cylinders should be hidden: we only have sources in different formats, RML Translators, Comunica and a SPARQL query. When activating Comunica, the data starts flowing between the different components: show the arrows (preferable with animation) and the RDF cylinders representing RDF data which is generated on the fly. Additionally, to complete this image, also an output file in e.g. CSV format can be added (with an arrow from Comunica). When Comunica is ready all arrows and the RDF containers should be hidden again. The RDF files are not saved anywhere as this is a representation of a virtual setup. The output file should stay visible. 

Please let me know if this is clear for you, and feel free to propose other ways to simulate the activation of components.

**Comment by TiboStr** [comment]
I imagine a 2-page application. In the first page you have all the space you need to write your config. There is a big button to add new editor areas. Each config resembles a 'step' in the visualization. If you click convert, each step is shown one by one so the result is (hopefully) a flow with smooth transitions.


The page where you can define your configs would look a bit like this (just a little prettier):

![Screenshot_20220812_115440](https://user-images.githubusercontent.com/71405687/184330850-885bb4cf-d0d7-482a-8feb-03603a929177.png)

**Comment by TiboStr** [comment]
- [x] Make the step buttons work
- [x] Import/export buttons on both pages
- [x] Buttons of snap to grid etc. on second page
- [x]  Individual import
- [x] Play simulation automatically when clicking on a 'play' button
- [x] Add example
- [x] YAML support (add language switcher button + make sure import/export can handle YAML)
- [x] Error handling (e.g. when JSON files are not correct ...)
- [x] Update README ...
