### ISSUE TITLE
Try out https://github.com/react-icons/react-icons#configuration as an alternative to SVGs

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#64]
Seems like you can set color and width etc etc of a [very big library of icons](https://react-icons.github.io/react-icons/search?q=database). Maybe that's easier than providing SVGs (at least for the icons case, having SVG support is very useful on its own!)
To overlay the text you can probably use standard CSS methods like [here](https://www.w3schools.com/howto/howto_css_image_text.asp).

**Comment by TiboStr** [comment]
Add a shape `icon`, that requires an extra key  `name`. `name` can be everything defined in the library. That way, the custom shapes stay (e.g. `comunica`) without messing up the autocompletion.

It won't be easy. I'd have to translate a string to a component somehow. [Using a hashmap for that](https://thewebdev.info/2021/11/06/how-to-render-a-string-as-react-component/) is really no option. Maybe [this library](https://github.com/PorUnaCabeza/string-to-react) is a solution.
