### ISSUE TITLE
There's duplication between configParsing and the schemas

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#65]
Can't your import the schema to set the description in the configParsing? Or is this automatically synced?

**Comment by TiboStr** [comment]
I don't think I understand 100% what you mean? Do you mean the `description`s in `configParsing` are duplicate with the descriptions in the schemas? 

While building the schemas, I iterate over the objects in `configParsing`.

**Comment by TiboStr** [comment]
Ah you mean duplication with the schemas in `schemas/schemas`? Or is it something else you mean?

**Comment by TiboStr** [comment]
Schemas are autogenrated.
