### ISSUE TITLE
Node label vs title: doesn't work?

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#69]
Looking at the documentation,

I would assume following

```JSON
{
	"shape": "comunica",
        "label": "OMG",
        "title": "LOL"
}
```

Would place OMG on top of the comunica logo, and LOL above it. Is this a bug or did I misinterpret the documentation?

**Comment by TiboStr** [comment]
You interpreted the documentation correctly. This is a bug.

**Comment by TiboStr** [comment]
Now it looks like this:
![Screenshot_20220810_131300](https://user-images.githubusercontent.com/71405687/183887565-284b1ff3-1fa7-409c-8960-a299913be87e.png)
